#!/bin/sh

# Author: Vendula Poncova
# Date: 14.4.2016
# Process results of analysis created by tools jbyco and analyze.
#
# Usage: 
#   ./jbyco-process input output max
#
# Parameters:
#   input   A file or a directory of .class and .jar files.
#   output  A directory for results of analysis.
#   max     Maximal number of summarized patterns of the same length.

#---------------------------------------------------------- settings

# include files
dir=$( cd $(dirname $0) ; pwd -P )
. "${dir}/jbyco-process-lib"

# process parameters
in=$1
out=$2
max=$3

# check input and output directory
for dir in "$in" "$out"; do
  if [ ! -d $dir ]; then
    echo "Directory $dir does not exist." 1>&2
    return 1
  fi
done

# reset default value  
if [ -z "$max" ]; then
  MAX_GROUP=100
else
  MAX_GROUP=$max
fi

#---------------------------------------------------------- main

echo "Generating directories." 1>&2
( 
  cd "$out";
  mkdir -p "basic";
  for dir in "." "if" "pop" "math" "begin" "null" "string"; do
    mkdir -p "$dir" "$dir/summary"
  done
)

echo "Generating basic cls files." 1>&2
generate_basic_cls $in "$out/basic"

echo "Generating merged and filtered cls files." 1>&2
for oi in "o1" "o2" ; do
  for pi in "p1" "p2" "p3"; do
    for w in "a" "x" "w"; do
          
      # merge
      file=$(merge_cls "$out/basic" $out $oi $pi $w)
          
      # summarize
      result=$(summarize_cls $file "$out/summary" $MAX_GROUP)
      
      # apply filters
      result=$(filter_and_summarize "$file" "$out" "if" "filter_end_with_if" $MAX_GROUP)
      result=$(filter_and_summarize "$file" "$out" "pop" "filter_end_with_pop" $MAX_GROUP)
      result=$(filter_and_summarize "$file" "$out" "math" "filter_end_with_math" $MAX_GROUP)
      result=$(filter_and_summarize "$file" "$out" "begin" "filter_begin_end" $MAX_GROUP)
      result=$(filter_and_summarize "$file" "$out" "null" "filer_null" $MAX_GROUP)
      result=$(filter_and_summarize "$file" "$out" "string" "filter_string " $MAX_GROUP)

    done
  done
done

# end of file
