#!/bin/sh

# Author: Vendula Poncova
# Date: 14.4.2016
# Process results of analysis created by tools jbyco and analyze.
#
# Usage: 
#   ./jbyco-process input output max
#
# Parameters:
#   input   A file or a directory of .class and .jar files.
#   output  A directory for results of analysis.
#   max     Maximal number of summarized patterns of the same length.

#---------------------------------------------------------- settings

# include files
dir=$( cd $(dirname $0) ; pwd -P )
. "${dir}/jbyco-process-lib"

# process parameters
in=$1
out=$2
max=$3

# check input and output directory
for dir in "$in" "$out"; do
  if [ ! -d $dir ]; then
    echo "Directory $dir does not exist." 1>&2
    return 1
  fi
done

# reset default value  
if [ -z "$max" ]; then
  MAX_GROUP=100
else
  MAX_GROUP=$max
fi

#---------------------------------------------------------- main

echo "Generating basic cls files."
generate_basic_cls $in $out

echo "Generating merged cls files."
for oi in "o1" "o2" ; do
  for pi in "p1" "p2" "p3"; do
    for w in "a" "x" "w"; do
          
      # merge
      file=$(merge_cls $in $out $oi $pi $w)
          
      # summarize
      result=$(summarize_cls $file $MAX_GROUP)
      
      # apply filters
      result=$(apply_filter $file "if" filter_end_with_if )
      result=$(summarize_cls $result $MAX_GROUP)
      
      result=$(apply_filter $file "pop" filter_end_with_pop )
      result=$(summarize_cls $result $MAX_GROUP)
      
      result=$(apply_filter $file "math" filter_end_with_math )
      result=$(summarize_cls $result $MAX_GROUP)
      
      result=$(apply_filter $file "begin" filter_begin_end )
      result=$(summarize_cls $result $MAX_GROUP)
      
      result=$(apply_filter $file "null" filer_null )
      result=$(summarize_cls $result $MAX_GROUP)
      
      result=$(apply_filter $file "string" filter_string )
      result=$(summarize_cls $result $MAX_GROUP)

      
    done
  done
done

# end of file
