#!/bin/sh

# Author: Vendula Poncova
# Date: 14.4.2016
# Library of functions for jbyca-postprocessing.
#
# Usage: 
#   source jbyca-postprocessing-lib

sort_cls() {
  sort -k 1,1n -k 3,3rg -k 2,2rn -k 4,4
};

unique_patterns() {
  awk -F "\t" '!counter[$4]++'
};

cut_patterns() {
  awk -F "\t" -v max="$1" 'counter[$1]++ < max'
};

skip_no_parameters() {

  # Find lines with numbered or full parameters, 
  # which are not only labels.
  
  grep -P ' (?!LABEL)[[:alpha:]]*\('
};

filter_same_parameters() {

  # Find lines with parameters of the same index.
  # example: STORE VAR(0); LOAD VAR(0);

  grep '\( [[:alpha:]]\+([[:digit:]]\+)\).*\1'
};

filter_p1() {
  grep '.'
};

filter_p2() {
  skip_no_parameters | filter_same_parameters
};

filter_p3() {
  skip_no_parameters
};

filter_end_with_if() {
  grep -P '; IF[^\;]*; $'
}

filter_end_with_pop() {
  grep -P '; POP[^\;]*; $'
}


filter_end_with_math() {
  grep -P '; [^\;]*(ADD|SUB|MUL|DIV|REM|NEG|SHL|SHR|AND|OR|XOR); $'
};

filter_begin_end() {
  grep -P '\tBEGIN;.*END; $'
};

filer_null() {
  grep -P 'null.*NULL'
};

filter_string() {
  grep -P 'CONST S.*StringBuilder'
};

remove_empty() {

  if [ ! -s "$1" ]; then
    rm -f "$1"
  fi

};

generate_basic_cls() {

  local in="$1"
  local out="$2"

  for input in $in/patterns*.out; do
    
    # check that file exists
    if [ ! -f $input ]; then
      continue
    fi
    
    # define name of output file
    output=$out/$(basename $input '.out')'.cls'
    
    # generate output
    tail -n +2 $input | \
    sort_cls > $output
    
    # remove file if empty
    remove_empty $output

  done
  
};

merge_cls() {

  local in="$1"
  local out="$2"
  local oi=$3
  local pi=$4
  local w=$5

  output="${out}/patterns_${oi}_${pi}_${w}.cls"
                
  # define output  
  if [ "$w" = "a" ]; then
    wregex="*" 
  elif [ "$w" = "x" ]; then
    wregex="0"
  else
    wregex="[1-9]*"
  fi

  # define names of input files
  name="patterns_${oi}_${pi}_${wregex}_*.cls"
        
  # define filter
  filter="filter_${pi}"

  # generate output                
  find "$out" -name "${name}" -exec cat {} \; | sort_cls \
  | unique_patterns \
  | $filter > $output
        
  # remove file if empty
  remove_empty $output
  
  # return name of file
  echo $output

};

apply_filter() {

  local in="$1"
  local out="$2"
  local suffix="$3"
  local filter="$4"
  
  # define input
  input="$in"
        
  # define output
  output=$out/$(basename $input '.cls')'_'${suffix}'.cls'
        
  # generate output
  cat "$input" 2>/dev/null | $filter > "$output"
        
  # remove file if empty
  remove_empty "$output"
  
  # return name of file
  echo $output

};

summarize_cls() {
  apply_filter "${1}" "${2}" "summary" "cut_patterns ${3}" 
};

filter_and_summarize() {
  
  local in="$1"
  local out="$2"
  local suffix="$3"
  local filter="$4"
  local max="$5"

  output=$(apply_filter "$in" "$out/$suffix" "$suffix" "$filter")
  output=$(summarize_cls "$output" "$out/$suffix/summary" "$max")

  echo $output

}


# end of file
