#!/bin/sh

# get input directory
input=$1

# create directory for outputs
name=$(date '+%Y_%m_%d_%H_%M_%S')
path="../output/$name"
mkdir -p $path
echo $path

# set lenght
length=25

# define function
analyzePatterns() {

  oi=$1
  pi=$2
  wi=$3

  # prepare args
  args="--analyze-patterns --max-length $length -w $wi -$oi -$pi $input"

  # prepare output
  filename="${path}/patterns_${length}_${wi}_${oi}_${pi}"
  echo $filename

  # run analysis
  { ./run $args 2>&3 | sort -k1,1nr -k2,2 >$filename.out ;} 3>&1 | tee -a ${filename}.err

};

# run analysis
#./run --analyze-size $input >$path/size.out 2>/dev/null
#./run --analyze-locals $input >$path/locals.out 2>/dev/null
#./run --stats $input >$path/stats.out 2>/dev/null

#analyzePatterns "o1" "p1" 0
#analyzePatterns "o2" "p3" 0
#analyzePatterns "o1" "p2" 0
#analyzePatterns "o1" "p2" 1
#analyzePatterns "o1" "p2" 2
#analyzePatterns "o2" "p3" 1

#analyzePatterns "o2" "p2" 0
#analyzePatterns "o2" "p2" 1
#analyzePatterns "o2" "p2" 2

analyzePatterns "o1" "p1" 1
analyzePatterns "o2" "p3" 2
analyzePatterns "o1" "p1" 2






